SELECT MTH
	,NEW_PRO
	,NEW_DELIVERIES AS NEW_PRO_DELIVERED
	,
	,NEW_DELIVERIES / NEW_ACTIVE_PRO AS NEW_PRO_UTIL
	,OLD_PRO
	,OLD_DELIVERIES AS OLD_PRO_DELIVERED
	,OLD_DELIVERIES / OLD_ACTIVE_PRO AS OLD_PRO_UTIL
FROM (
	SELECT extract(month FROM BDATE_FINAL) AS MTH
		,count(DISTINCT RESPONDED_PRO_BOOKING) AS NEW_PRO
		,
		,COUNT(DISTINCT USER_ID) AS NEW_DELIVERIES
		,COUNT(DISTINCT CASE 
				WHEN RESPONDED_PRO_BOOKING IS NOT NULL
					THEN USER_ID
				END) AS NEW_ACTIVE_PRO
		,count(DISTINCT CASE 
				WHEN extract(month FROM BDATE_FINAL) <> MONTH(NOW())
					AND extract(year FROM BDATE_FINAL) = YEAR(NOW())
					THEN RESPONDED_PRO_BOOKING
				END) AS REPEAT_PRO
		,
		,count(DISTINCT CASE 
				WHEN extract(month FROM BDATE_FINAL) <> MONTH(NOW())
					AND extract(year FROM BDATE_FINAL) = YEAR(NOW())
					THEN USER_ID
				END) AS OLD_DELIVERIES
		,
		,count(DISTINCT CASE 
				WHEN extract(month FROM BDATE_FINAL) <> MONTH(NOW())
					AND extract(year FROM BDATE_FINAL) = YEAR(NOW())
					AND RESPONDED_PRO_BOOKING IS NOT NULL
					THEN USER_ID
				END) AS OLD_ACTIVE_PRO
	FROM SQL_TEST
	GROUP BY 1
	ORDER BY 1
	) AS t
