
SELECT MTH
	,PRO_STATE
	,ACTIVE_PRO
	,CHURN_PRO
	,(round(((CHURN_PRO * 100.0) / NULLIF(ACTIVE_PRO, 0.00)), 2) || '%') AS CHURN_PRO_PERCENTAGE
FROM (
	SELECT extract(month FROM BDATE_FINAL) AS MTH
		,COUNT(DISTINCT CASE 
				WHEN RESPONDED_PRO_BOOKING IS NOT NULL
					THEN USER_ID
				END) AS ACTIVE_PRO
		,COUNT(DISTINCT CASE 
				WHEN RESPONDED_PRO_BOOKING IS NULL
					THEN USER_ID
				END) AS CHURN_PRO
		,CASE 
			WHEN extract MONTH(DATEADD(mm, - 1, GETDATE())) <= MONTH(NOW())
				OR (
					extract month FROM BDATE_FINAL
					) = MONTH(NOW())
				THEN ‘REPEAT’
			WHEN (
					extract month FROM BDATE_FINAL
					) = MONTH(NOW())
				OR extract(month FROM BDATE_FINAL) <> MONTH(NOW())
				THEN ‘REACTIVE’
			ELSE ‘NEW’
			END
	) AS PRO_STATE
FROM SQL_TEST
GROUP BY 1
	,4
ORDER BY 1 ) AS t

